### ISSUE TITLE
getting this error!!! Pls help on this

### ISSUE THREAD

**Issue by prabhinmp** [petrushinvs/mongodb-zabbix-templates-4.0#3]
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/mongod-db.py", line 35, in <module>
    r = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by petrushinvs** [comment]
Hello, prabhinmp, please install latest mongodb-org-tools and mongodb-org-shell packages. It tries to find and execute mongostat command in PATH.

**Comment by prabhinmp** [comment]
As you said installed the required package, still no data fetched from the mongodb server.

**Comment by mihica123** [comment]
I confirm this problem. 
`Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/mongod-db.py", line 35, in <module>
    r = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

both packages mongodb-org-tools and mongodb-org-shell up to date

**Comment by petrushinvs** [comment]
This because of subprocess.Popen(...) can't find mongostat binary in PATH. I can't reproduce it in Ubuntu and have no capabilities to debug it in Centos/RHEL. You can fix it yourself.
In line 34 cmd = ['mongostat', "-u", muser, "-p", mpass, "-h",.... add full path to mongostat binary.
Like this
cmd = ['/full/path/to/mongostat', "-u", muser, "-p", mpass, "-h",...

**Comment by goat90** [comment]
Hi, I have the same error code.
Even if I add full path to mongostat it doesn't work:
_cmd = ['/bin/mongostat', "-u", muser, "-p", mpass, "-h", mongohost + ":" + mongoport, "--authenticationDatabase=admin", "--rowcount", "1", "--noheaders"]_

_FileNotFoundError: [Errno 2] No such file or directory: '/bin/mongostat'_
Same with /usr/bin/mongostat

My setup is Ubuntu 20.04 with latest mongotols:
ii  mongodb-database-tools               100.2.1                                    amd64        mongodb-database-tools package provides tools for working with the MongoDB server:
ii  mongodb-org                          4.4.2                                      amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-database-tools-extra     4.4.2                                      amd64        Extra MongoDB database tools
ii  mongodb-org-mongos                   4.4.2                                      amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                   4.4.2                                      amd64        MongoDB database server
ii  mongodb-org-shell                    4.4.2                                      amd64        MongoDB shell client
ii  mongodb-org-tools                    4.4.2                                      amd64        MongoDB tools
ii  php-mongodb                          1.6.1-4build1                              amd64        MongoDB driver for PHP

I would be grateful for any tip.
